### ISSUE TITLE
NethCTI 2: chat does not work after ejabberd upgrade

### ISSUE THREAD

**Issue by alepolidori** [nethesis/dev#5458]
**Steps to reproduce**

- start from a cti2 installation with `ejabberd-16.01-0.x86_64` and `nethserver-ejabberd-1.1.5-1.ns7.noarch`
- verify that chat works
- update to `ejabberd-18.06-0.x86_64` and `nethserver-ejabberd-1.2.0-1.ns7.noarch`
- chat does not work anymore: from the speed dial contacts no chat icon is present

**Expected behavior**

The chat continues to work

**Actual behavior**

There are not any chat icon on speed dial contacts. It is not possible to chat with nobody.

**Components**

- NethCTI client
- NethVoice 11 and CTI 2 on NethServer 7

**Possible solution**
The cti client can login to ejabberd server, so probably the parsing of received xmpp messages has been broken.

**Comment by nrauso** [comment]
Tested: patch works only if you use machine fqdn to connect to CTI.
If you would use a different url (you can specify a different url for http-bind with `JabberUrl` prop of `nethcti-server` db configuration record) chat doesn't work.
It should work even if used with different url.
