### ISSUE TITLE
NethVoice 11: visualplan groups members doesn't work with # 

### ISSUE THREAD

**Issue by SebastianMB-IT** [nethesis/dev#5468]
A member can't be added with # on the end

**Steps to reproduce**

- Try to create a group and a member extension with # on the end
- Note that in ring groups extension list the extension is added without #

**Expected behavior**

- If  member is added with # the visual plan should leave the member untouched

**Actual behavior**

- '#' is removed from member extension

**Components**

nethvoice-module-nethvplan11-1.1.3-1.ns7.noarch

**See also**

https://github.com/nethesis/nethvoice-module-nethvplan/commit/2237784d21727661f64894ec1ad40eecf9f2acd2

**Comment by SebastianMB-IT** [comment]
nethesis-testing
- http://packages.nethesis.it/nethserver/enterprise/7.5.1804/nethesis-testing/x86_64/Packages/nethvoice-module-nethvplan11-1.1.3-1.1.gdae4942.ns7.noarch.rpm

**Comment by SebastianMB-IT** [comment]
**Test**

- Create a group and check that members with # are correctly saved

**Comment by Stell0** [comment]
This issue was incorrect, check the new issue: https://github.com/nethesis/dev/issues/5469
