### ISSUE TITLE
Reports: email virus always 0

### ISSUE THREAD

**Issue by filippocarletti** [nethesis/dev#5543]
**Steps to reproduce**

- Update to rspamd 1.8.2
- Run `weekly-report`
- Found virus equals to 0

**Expected behavior**

maillog has many "virus found" messages

**Components**

nethserver-report-1.2.8-1.ns7.noarch

**Comment by filippocarletti** [comment]
rspamd changed output format.
A new regexp to count virii is in
https://github.com/nethesis/nethserver-report/commit/cdffd0a201bb1737e4aacd2317803b3d1dffc002

**Comment by gsanchietti** [comment]
In nethesis-updates:
nethserver-report-1.8.1-1.ns7.noarch.rpm
