### ISSUE TITLE
NS6: remove legacy SOAP client

### ISSUE THREAD

**Issue by gsanchietti** [nethesis/dev#5552]
The registration of a server must use the new method implemented in nethesis/dev#5540

**Steps**

- [x] Make sure the non-authenticated access to Software Center redirects to subscription module
- [x] Remove legacy SOAP client for server registration

**Comment by gsanchietti** [comment]
**Test case 1**
- Install from  ISO
- Access the Software Center
- Check the browser is redirected to "Subscription" form
- Register the machine to my.nethesis.it
- Check the server has a valid System ID and can access yum repositories

**Test case 2**
- After test case 1
- Access the Software Center which must requires the reseller credentials
- Authenticate with **invalid* credentials, check the Software Center is not accessible

**Test case 3**
- After test case 1
- Access the Software Center which must requires the reseller credentials
- Authenticate with valid credentials, check the Software Center is fully functional

**Test case 4**
- Update an existing machine
- Check the test Software Center works as described in test case 2
- Check the "Registration" page correctly reports the System ID
- Check the server can  access yum repositories

**Comment by gsanchietti** [comment]
In `6.10/nethesis-testing`:
- nethserver-register-2.3.1-1.1.g493b28c.ns6.noarch.rpm

**Comment by Ilvo** [comment]
**Test case 1 tested**

_browser is redirected to "Subscription" form_

![reg](https://user-images.githubusercontent.com/36000560/50964008-893ff780-14ce-11e9-9b8a-94726dc749ed.png)

_server has a valid System ID_

![id](https://user-images.githubusercontent.com/36000560/50963467-12eec580-14cd-11e9-9836-6a317cc2dcbd.png)

_server can access yum repositories_

```
[root@610test ~]# yum repolist
Loaded plugins: changelog, fastestmirror, nethserver_events, presto
Loading mirror speeds from cached hostfile
 * nethesis-support: u1.nethserver.com
 * nh-centos-base: u1.nethserver.com
 * nh-nethserver-base: u1.nethserver.com
repo id                                  repo name                                            status
nethesis-support                         Nethesis Support 6.10                                    8
nethesis-updates                         Nethesis Updates 6.10                                  291
nethesis-upstream                        Nethesis Upstream 6.10                                 257
nh-centos-base                           Nethesis CentOS Base 6.10                            6,713
nh-nethserver-base                       Nethesis NethServer Base 6.10                          506
repolist: 7,775
```


**Test case 2 tested**

_Authenticate with *invalid credentials, check the Software Center is not accessible_

![invalid_cred](https://user-images.githubusercontent.com/36000560/50963069-fef69400-14cb-11e9-9569-9228bae7ffa9.png)

**Test case 3 tested**

_Authenticate with valid credentials, check the Software Center is fully functional_

![schermata da 2019-01-10 10-00-27](https://user-images.githubusercontent.com/36000560/50963145-2d746f00-14cc-11e9-9c81-24e44c73458d.png)

**Test case 4 tested**

_Update an existing machine_

old machine update with

`yum --enablerepo=nethesis-testing install nethserver-register`

_Authenticate with *invalid credentials, check the Software Center is not accessible_

![invalid_cred](https://user-images.githubusercontent.com/36000560/50963069-fef69400-14cb-11e9-9569-9228bae7ffa9.png)


_server can access yum repositories_

```
[root@610test ~]# yum repolist
Loaded plugins: changelog, fastestmirror, nethserver_events, presto
Loading mirror speeds from cached hostfile
 * nethesis-support: u1.nethserver.com
 * nh-centos-base: u1.nethserver.com
 * nh-nethserver-base: u1.nethserver.com
repo id                                  repo name                                            status
nethesis-support                         Nethesis Support 6.10                                    8
nethesis-updates                         Nethesis Updates 6.10                                  291
nethesis-upstream                        Nethesis Upstream 6.10                                 257
nh-centos-base                           Nethesis CentOS Base 6.10                            6,713
nh-nethserver-base                       Nethesis NethServer Base 6.10                          506
repolist: 7,775
```

**Comment by gsanchietti** [comment]
ISO available here: http://birro.nethesis.it/install/nethserver/enterprise/iso/nethserver-enterprise-6.10.1-x86_64.iso
