### ISSUE TITLE
NethCTI 3: log as warn when a user deletes an offhour audio message

### ISSUE THREAD

**Issue by alepolidori** [nethesis/dev#5565]
**Description**

It is useful to know who have removed an audio message used for offhour service.
Log it as a `WARN` message.

**Components**

cti server

**Comment by alepolidori** [comment]
in `nethesis-testing`:

- http://packages.nethesis.it/nethserver/enterprise/7.6.1810/nethesis-testing/x86_64/Packages/nethcti-server3-3.6.0-1.2.g0ad3368.ns7.x86_64.rpm

**Comment by alepolidori** [comment]
**How to test**

- delete an offhour audio message and verify that a new warning message has been added to the log `/var/log/asterisk/nethcti.log`

**Comment by andrea-marchionni** [comment]
2019-01-18T17:18:29+01:00 - warn: [plugins_rest/offhour] deleted announcement "22" by user "andrea"

**Comment by alepolidori** [comment]
in `7.6.1810/nethesis-updates`:

- http://packages.nethesis.it/nethserver/enterprise/7.6.1810/nethesis-updates/x86_64/Packages/nethcti-server3-3.7.0-1.ns7.x86_64.rpm
