### ISSUE TITLE
NethCTI 2: rest api login from another domain - CORS policy

### ISSUE THREAD

**Issue by nic86** [nethesis/dev#5614]
**Steps to reproduce**

Test code to make the error happen:

```
<hmtl>
<head>

<script>
function doLogin () {
    var data = JSON.stringify({
          "username": "myuser",
          "password": "mypass"
    });   
    
    var xhr = new XMLHttpRequest();

    xhr.addEventListener("readystatechange", function () {
          if (this.readyState === 4) {
            var response = xhr.getResponseHeader('www-authenticate');
        }   

    });

    xhr.open("POST", "https://192.168.5.210/webrest/authentication/login");
    xhr.setRequestHeader("Content-Type", "application/json");

    xhr.send(data);
}
</script>
</head>
<body>
<input id="login" type="button" value="login" onclick="doLogin();" />
</body>
</html>
```

**Expected behavior**

When the login button is clicked the code in the doLogin function is executed. 
At the end of it, when the XMLHttpRequest.readyState is equal to 4 (done), the variable 'response' should have the header 'www-authenticate' value.

**Actual behavior**

The variable 'response' always gets 'null' value.
From the console I get the following error message:
Access to XMLHttpRequest at 'https://192.168.5.210/webrest/authentication/login' from origin 'http://login.test.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

But from the network panel the header 'www-authenticate' has the correct value as shown in the following screenshot:

![Schermata da 2019-04-12 11-06-59](https://user-images.githubusercontent.com/18703633/56026070-ae354800-5d13-11e9-9048-75e0326b6853.png)

**Components**

Client:nethcti-2.6.8-1.ns6.noarch
Server:nethcti-server-2.6.11-1.ns6.x86_64

**Comment by alepolidori** [comment]
Sorry, but NethCTI version 2 does not support cross-domain requests.
Your problem is that network panel shows www-authenticate header but you don't have it from the code ?

**Comment by nic86** [comment]
yes, I would like to create a javascript plugin to integrate it into our system that allows it to make calls to the nethevoice PBX VoIP server using the api rest {{base_url}}/astproxy/call but to do so i need that www-authenticate header returns the proper value to the code. Thanks

**Comment by alepolidori** [comment]
I close the issue because NethCTI 2 is no more developed.
The advice is to migrate to NethCTI 3 that support CORS.
