### ISSUE TITLE
Show online notification for QManager dashboard alarms

### ISSUE THREAD

**Issue by alepolidori** [nethesis/dev#5632]
**Description**

When you receive a new alarm into the QManager dashboard, the alarm has to be showed also into the top bar notification icon.
Clicking on it the user can show the notification and clicking again on the specific notification, the QManager dashboard will appears.

**Components**

nethcti client

**Comment by alepolidori** [comment]
The inactivity was caused by vacations: I re-open it

**Comment by andrea-marchionni** [comment]
Issue to be resolved on interface restyling
