### ISSUE TITLE
NethVoice14: collectd restart fails if asterisk is stopped

### ISSUE THREAD

**Issue by filippocarletti** [nethesis/dev#5657]
**Steps to reproduce**

- systemctl stop asterisk
- systemctl restart collectd
- systemctl status collectd
```
collectd[25129]: Unhandled python exception in loading module: TypeError: not all arguments
```

**Expected behavior**

collectd should always run

**Actual behavior**

collectd not running

Note: on boot, if asterisk doesn't start (or it's slow) collectd will not start: no alarms at all.

**Comment by Stell0** [comment]
should be fixed by https://github.com/nethesis/dev/issues/5621
