### ISSUE TITLE
Wrong buttons display into the left advanced operator panel side

### ISSUE THREAD

**Issue by alepolidori** [nethesis/dev#5697]
**Steps to reproduce**

- Use a 15,6" screen with 1366x768 resolution
- login to cti
- verify that buttons on left side panel are wrong aligned as showed below:
![image](https://user-images.githubusercontent.com/1625334/64855939-39976a00-d621-11e9-9589-a8872bf21c05.png)

**Expected behavior**

Buttons have to be showed correctly without zoom out

**Actual behavior**

Wrong visualization of the buttons

**Components**

cti client

Reported By: AndreaG

**Comment by andrea-marchionni** [comment]
Issue to be resolved on interface restyling, add to project todo list
