### ISSUE TITLE
Weekly reports: allow the user to enter a custom time interval

### ISSUE THREAD

**Issue by andre8244** [nethesis/dev#5698]
Allow the user to enter a custom time interval.
Currently only these time intervals are supported:
- last week
- last month
- last six monts

**Components**

nethesis-dante

**Comment by andre8244** [comment]
Test case:

- Install or update `nethserver-dante` package
- If it's a fresh installation, go to `Settings` page of `Weekly reports` application on Cockpit and click `Collect now` button
- Go to `Dashboard` page and click `Custom interval` button
- End date is set to today by default. Choose start date in the date picker and verify that the report reloads showing information relevant to the custom time interval
- Verify that changing end date and/or start date the report refreshes showing the appropriate data

**Comment by edospadoni** [comment]
in `7.7.1908/testing`:
- [dante](http://packages.nethserver.org/nethserver/7.7.1908/testing/x86_64/Packages/dante-0.1.4-1.1.g8410aa8.ns7.x86_64.rpm)

**Comment by gsanchietti** [comment]
Released: dante-0.2.0-1.ns7.x86_64.rpm
