### ISSUE TITLE
Icaro: bug fixes and UI improvements

### ISSUE THREAD

**Issue by andre8244** [nethesis/dev#5706]
- Toggle voucher visibility during login
- Set delay of automatic sending of feedback email in minutes instead of hours
- Fix CSV export on Firefox
- Fix login with voucher expired
- New voucher design
- Voucher expiration at the end of the day
- Search vouchers by creation and expiration dates

**Comment by andre8244** [comment]
**NOTE**: before the release the preexisting delay values of feedback email on the database must be converted in minutes. https://github.com/nethesis/icaro/pull/116#issue-322805752

**Comment by mamengoni** [comment]
Tested : ok

**Comment by edospadoni** [comment]
Released on: https://github.com/nethesis/icaro/commit/fc6fe99bd56c07893719ad483d19c39b877c19ce (v61)
