### ISSUE TITLE
Icaro: voucher search is case sensitive

### ISSUE THREAD

**Issue by andre8244** [nethesis/dev#5718]
**Steps to reproduce**

- Go to "Hotspots" section and click on a hotspot
- Filter vouchers list by typing a valid voucher code in uppercase
- Click "Apply filters" button

**Expected behavior**

Voucher list is filtered and shows one voucher

**Actual behavior**

Voucher list is filtered but no voucher is found

**Components**

icaro

**Comment by edospadoni** [comment]
Check the bug is not reproducible

**Comment by edospadoni** [comment]
Tested: **OK**
