### ISSUE TITLE
Picking-up a parked call coming from a queue, does not work

### ISSUE THREAD

**Issue by alepolidori** [nethesis/dev#5720]
**Steps to reproduce**

- receive a call from a queue
- answer and park the call
- make a pickup and verify that it does not work

**Expected behavior**

Pickup works correctly

**Actual behavior**

Pickup does not work

**Cause**

The cti server parks the call correctly using the channel of the extensions e.g. SIP/206-0000021a, but than asterisk makes a channel swap changing the channel name. Than the cti client make a pickup parking using the old channel.

**Solution**

Cti server has to get the parked channel on the specific parking before make the pickup itself.

**Components**

cti server

**Comment by andrea-marchionni** [comment]
Issue to be resolved on interface restyling, add to project todo list
