### ISSUE TITLE
After filtering user list in the operator panel, the contextual menu of boxes don't appear anymore

### ISSUE THREAD

**Issue by alepolidori** [nethesis/dev#5727]
**Steps to reproduce**

- open the operator panel
- verify that the menu on each user work properly
- filter user list inserting text into the relative input box
- remove the filter
- verify that menu does not work anymore for that users that has been cut off by the filer

**Expected behavior**

Menu has to be work after the filtering

**Actual behavior**

Menu does not work anymore after the filtering for that user that has been cut off by the filter

**Components**

nethcti3

**See also**

![image](https://user-images.githubusercontent.com/1625334/67484617-c1cd4e00-f668-11e9-9be0-09878533e52b.png)

**Comment by andrea-marchionni** [comment]
Issue to be resolved on interface restyling, add to project todo list
