### ISSUE TITLE
Nethifier: custom notification popup is not definitive

### ISSUE THREAD

**Issue by andrea-marchionni** [nethesis/dev#5734]
If I want to customize Nethifier notification popup changing some present button, for example, Customer card button, I can't.
If I modify 

/usr/lib/node/nethcti-server/plugins/com_static_http/static/templates/notification_popup/call.html

as the documentation says the change is lost on the first update, it is not a configuration file.

If I add 

/var/lib/nethserver/nethcti/static/templates/notification_popup/call.html

this file is not used if there is 

/usr/lib/node/nethcti-server/plugins/com_static_http/static/templates/notification_popup/call.html

**Steps to reproduce**

- modify /usr/lib/node/nethcti-server/plugins/com_static_http/static/templates/notification_popup/call.html
- update nethcti-server3 package

- add /var/lib/nethserver/nethcti/static/templates/notification_popup/call.html
- remove /usr/lib/node/nethcti-server/plugins/com_static_http/static/templates/notification_popup/call.html
- update nethcti-server3 package

**Expected behavior**

An effective procedure to change the Nethifier notification popup.

**Actual behavior**

The change is lost or not used.

**Components**

nethcti-server3

**Comment by alepolidori** [comment]
As a solution we thought of give more priority to popup templates present into `/var/lib/nethserver/nethcti/static/templates/notification_popup/call.html` and this for all type of file that are not a temporary file used to provide record files for example.

**Comment by andrea-marchionni** [comment]
Issue to be resolved on interface restyling, add to project todo list
