### ISSUE TITLE
NethCTI 3 client: no hangup on outgoing call

### ISSUE THREAD

**Issue by alepolidori** [nethesis/dev#5736]
**Steps to reproduce**

- make an outgoing call
- the destination does not answer
- using webrtc you cannot hangup the call

**Expected behavior**

The user can hangup the call

**Actual behavior**

The user cannot hangup the call

**Components**

cti client

**Comment by alepolidori** [comment]
This bug is caused by a Janus-Gateway bug: https://github.com/meetecho/janus-gateway/issues/1856

**Comment by alepolidori** [comment]
Mark as verified when the https://github.com/nethesis/dev/issues/5737 is

**Comment by federicoballarini** [comment]
Updated janus library and now it works properly.
