### ISSUE TITLE
Reload httpd config on trusted-networks-modify event

### ISSUE THREAD

**Issue by Stell0** [nethesis/dev#5759]
at the moment, httpd configuration is expanded and reload only at interface update event, but it should be in trusted-networks-modify, because trusted networks are in httpd confguration

**Comment by DavidePrincipi** [comment]
@Stell0 could you add a test case too?

**Comment by Stell0** [comment]
Test case:
- modify trusted network and check that httpd configuration is expanded and httpd reloaded
- modify interface network and check that httpd configuration is expanded and httpd reloaded

**Comment by DavidePrincipi** [comment]
**VERIFIED**

When the trusted-networks-modify event is triggered the expected template expansion and httpd reload occurs.

**Comment by Stell0** [comment]
in `7.7.1908/nethesis-updates`:
- nethserver-nethvoice14-14.6.3-1.ns7.noarch.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.7.1908/nethesis-updates/x86_64/Packages/nethserver-nethvoice14-14.6.3-1.ns7.noarch.rpm)
