### ISSUE TITLE
Phone number can't be saved in configuration page

### ISSUE THREAD

**Issue by SebastianMB-IT** [nethesis/dev#5768]
Phone number is not correctly saved in Configurations page.

**Components**

nethvoice-wizard-ui

**Comment by DavidePrincipi** [comment]
**VERIFIED** by @andrea-marchionni

**Comment by Stell0** [comment]
in `7.7.1908/nethesis-updates`:
- nethvoice-wizard-ui-14.4.2-1.ns7.noarch.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.7.1908/nethesis-updates/x86_64/Packages/nethvoice-wizard-ui-14.4.2-1.ns7.noarch.rpm)
