### ISSUE TITLE
Weekly reports: content filter miner error

### ISSUE THREAD

**Issue by nrauso** [nethesis/dev#5794]
If you install and enable proxy web and web content filter, content filter related miners of new weekly report will generate an error:
```
/usr/share/dante/miners/squidguardsites-list
Traceback (most recent call last):
  File "/usr/share/dante/miners/squidguardsites-list", line 47, in <module>
    blocked_lines = squidguardlib.grep_blocked_lines()
  File "/usr/lib/python2.7/site-packages/squidguardlib.py", line 67, in grep_blocked_lines
    previous_log_file = find_most_recent(log_directory, "ufdbguardd.log-")
  File "/usr/lib/python2.7/site-packages/squidguardlib.py", line 42, in find_most_recent
    return max(name_n_timestamp, key=lambda k: name_n_timestamp.get(k))
ValueError: max() arg is an empty sequence
```
This seems to happen because those miners search for old ufdbguardd log files that are not present on newly installed web content filter.
As soon as the system rotates the logs the problem disappears.

Maybe @edospadoni and @andre8244 can help to better analyze the issue! :)

**Steps to reproduce**

- Install and enable proxy web and web content filter
- Wait for the weekly report to execute and look for the mail it generates to root or run from terminal:
   ```
   sh -x /usr/bin/ciacco
   ```

**Expected behavior**

Miners should fetch the data without errors even in freshly installed systems

**Actual behavior**

`root` receives a mail with a weird - but harmless - python error

**Components**

dante-0.3.0-1.ns7.x86_64
nethserver-dante-1.0.2-1.ns7.noarch

**Comment by edospadoni** [comment]
Test case:
- check the bug is not reproducible

**Comment by nrauso** [comment]
Tested: **verified**

No more error appears.

**Comment by gsanchietti** [comment]
Released:
dante-0.4.0-1.ns7.x86_64.rpm
