### ISSUE TITLE
Development builds for Janus and sofia-sip

### ISSUE THREAD

**Issue by DavidePrincipi** [nethesis/dev#5836]
To troubleshoot random janus-gateway server crashes it is sometimes necessary to rebuild the binary package with additional development libraries, such as libasan and libubsan.

Those libraries send a detailed trace of what happens to **stdout**. By now the `janus-gateway.service` Systemd unit suppresses stdout completely and relies on the builtin janus file logger.

As additional limitation, the builtin janus file logger does not integrate well with logrotate: it requires a `copytruncate` mode that is not optimal (it might loose some lines...). 

**Proposed solution**

- [x] Pass additional dev-mode compilation flags to makerpms conditionally, when a PR build starts
- [x] Build without dev-mode libraries for testing and final release
- [x] Document how to start Janus with detailed log trace
- [x] Fix the logrotate configuration behavior for `/var/log/janus` to obey to global system settings (rotate times, frequency, compress...)
- [x] Configure janus for minimal log details by default. Allow to raise the verbosity with the admin API

**Alternative solutions**

We run this kind of builds manually, but it is hard to set up a building environment in a private VM or similar. Instead build reproducibility and simplicity must be available quickly when a problem occurs.

**Comment by DavidePrincipi** [comment]
**Test case**

1. check that when a PR is opened for janus-gateway or sofia-sip the automatically built package dynamically links to libasan and libubsan (janus only)
2. check that testing and release builds do not link to libasan and libubsan
3. follow the README.rst instructions and ensure the documented procedure actually enables a detailed trace and sends it to `/var/log/janus-trc.log.PID`. Do the clean up too
4. run `logrotate -f /etc/logrotate.conf` and check the normal janus log is rotated according to system policy
5. test the admin API can be reached by following the documented procedure (README.rst of nethserver-janus)

**Comment by gsanchietti** [comment]
Development builds are good but problems still persist on normal builds: there no way to publish to updates using travis.

I have manually built all dependencies for current release, I leave this issue open since it requires further development.

**Comment by DavidePrincipi** [comment]
In nethserver-updates:

http://packages.nethserver.org/nethserver/7.8.2003/updates/x86_64/Packages/janus-gateway-0.10.2-2.ns7.x86_64.rpm

**Comment by DavidePrincipi** [comment]
**VERIFIED**

2 & 5 are verified too
