### ISSUE TITLE
Weekly reports: nextcloud miner error

### ISSUE THREAD

**Issue by nrauso** [nethesis/dev#5842]
On fresh installation of NethServer with Nextcloud, `weekly-report` generates an error fetching Nextcloud data:
```
malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "(end of string)") at /usr/share/dante/miners/nextcloudsize-list line 40.
```
The command that fails (line `40` inside `/usr/share/dante/miners/nextcloudsize-list`) is:
```
my $users = decode_json(`su - apache -s /bin/bash -c "source /opt/rh/rh-php72/enable; cd /usr/share/nextcloud/; php occ --output=json user:list" 2>/dev/null`);
```
This seems to happen because Nextcloud miner tries to use an unavailable version of `PHP`:
```
~]# su - apache -s /bin/bash -c "source /opt/rh/rh-php72/enable; cd /usr/share/nextcloud/; php occ --output=json user:list"
-bash: /opt/rh/rh-php72/enable: No such file or directory
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /usr/share/nextcloud/console.php on line 97
```
In fact, on new systems `PHP72` is no more avaliable:
```
~]# scl -l
rh-php73
```
To workaround the problem you could change the hard-coded path of PHP inside the script (`php72` -> `php73`).

**Steps to reproduce**

- Install a brand new NethServer, then install Nextcloud
- Wait for the weekly report to execute and look for the mail it generates to root or run from terminal:
  ```
  sh -x /usr/bin/ciacco
  ```

**Expected behavior**

Miner should fetch the data without errors even in freshly installed systems

**Actual behavior**

`root` receives a mail with a weird - but harmless - `"malformed JSON string"` error

**Components**

dante-0.4.0-1.ns7.x86_64
nethserver-dante-1.0.2-1.ns7.noarch

**Comment by gsanchietti** [comment]
In testing:
dante-0.4.0-1.1.g1dd8c7d.ns7.x86_64.rpm

**Comment by gsanchietti** [comment]
**Test case**
Check the bug is not reproducible

To install the package: `yum --enablerepo=nethserver-testing update dante`

**Comment by nrauso** [comment]
Tested: **verifed**

Now the miner works as expected.

**Comment by gsanchietti** [comment]
Released in nethserver-updates:
dante-0.4.1-1.ns7.x86_64.rpm
