### ISSUE TITLE
Cockpit: enhance rebranding

### ISSUE THREAD

**Issue by andre8244** [nethesis/dev#5843]
Extend rebranding on Cockpit after server registration by showing reseller logo, website and product name in:
- **About** page inside **System** section
- Nethesis Launcher

**Components**
- `noc-onrun`
- `nethserver-register`
- `nethserver-cockpit`
- `nethserver-subscription`

**See also**

nethesis/dev#5757

**Comment by andre8244** [comment]
**Test case 1 (NethServer Community)**

- Update `nethserver-cockpit` and `nethserver-subscription` on NethServer Community (testing RPM [here](https://github.com/nethesis/dev/issues/5843#issuecomment-659418868))
- Verify that **Community app launcher** (https://server) works as expected
- Go to Cockpit **System** > **About** page
- Verify that 
  - NethServer logo is shown
  - **Official site** links to https://www.nethserver.org/
  - **Documentation** links to http://docs.nethserver.org/
  - **Helpdesk** links to https://community.nethserver.org/
  - **Phone Home** section is shown

**Comment by andre8244** [comment]
**Test case 2 (NethServer Enterprise)**

- Update `nethserver-cockpit`, `nethserver-subscription` and `nethserver-register` on NethServer Enterprise (testing RPM [here](https://github.com/nethesis/dev/issues/5843#issuecomment-659418868))
- Verify that **Nethesis launcher** (https://server) works as expected
- Go to Cockpit **System** > **About** page
- Verify that 
  - Nethesis logo is shown
  - **Official site** links to https://nethesis.it/
  - **Documentation** links to https://docs.nethesis.it/
  - **Helpdesk** links to https://helpdesk.nethesis.it/
  - **Phone Home** section is NOT shown

**Comment by andre8244** [comment]
**Test case 3 (Branding)**

- Update `nethserver-cockpit`, `nethserver-subscription` and `nethserver-register` on NethServer Enterprise (testing RPM [here](https://github.com/nethesis/dev/issues/5843#issuecomment-659418868))
- Go to https://my.nethesis.it/
- If needed, access as distributor and grant **Branding** capability to the reseller of the NethServer you are using for the test
- Access https://my.nethesis.it/ as the reseller of the NethServer you are using for the test
- Go to **Profile** page
- Create a new brand using **Rebrand** section:
  - Choose **Base product: NethServer 7**
  - Enter a **Name** for the product containing one or more spaces, e.g.: **My custom NS**
  - Fill in **Site**, **Docs URL**, **Logo** and **Favicon**
  - Click **Save** and verify that a validation error about product name is shown
  - Enter a valid **Name** (remove spaces) and click **Save**
- Execute `signal-event -j nethserver-register-update && systemctl restart cockpit` on the server
- Verify that **App launcher** (https://server) is now rebranded with product name, logo, website and documentation links
- Access Cockpit login page and verify custom product name, logo and favicon are shown
- Go to Cockpit **System** > **About** page and verify that:
  - Custom logo is shown
  - **Official site** links to custom URL
  - **Documentation** links to custom URL
  - **Helpdesk** button is NOT shown
  - **Phone Home** section is NOT shown

**Comment by andre8244** [comment]
**Testing RPM**
- [nethserver-cockpit](http://packages.nethserver.org/nethserver/7.8.2003/autobuild/x86_64/Packages/nethserver-cockpit-1.7.5-1.2.pr280.g58f914a.ns7.noarch.rpm)
- [nethserver-cockpit-lib](http://packages.nethserver.org/nethserver/7.8.2003/autobuild/x86_64/Packages/nethserver-cockpit-lib-1.7.5-1.2.pr280.g58f914a.ns7.noarch.rpm)
- [nethserver-register](http://packages.nethesis.it/nethserver/enterprise/7.8.2003/nethesis-autobuild/x86_64/Packages/nethserver-register-4.5.1-1.11.pr67.gc480e09.ns7.noarch.rpm)
- [nethserver-subscription](http://packages.nethserver.org/nethserver/7.8.2003/autobuild/x86_64/Packages/nethserver-subscription-3.6.1-1.2.pr34.g97e15f2.ns7.noarch.rpm)
- [nethserver-subscription-ui](http://packages.nethserver.org/nethserver/7.8.2003/autobuild/x86_64/Packages/nethserver-subscription-ui-3.6.1-1.2.pr34.g97e15f2.ns7.noarch.rpm)

**Comment by andre8244** [comment]
**Test case 4 (Unbranding)**

- Complete **Test case 3 (Branding)**
- Access https://my.nethesis.it/ as the reseller of the NethServer you are using for the test
- Go to **Profile** page
- Select **NethServer 7** rebranding and delete it
- Execute `signal-event -j nethserver-register-update && systemctl restart cockpit` on the server
- Verify that **Nethesis launcher** (https://server) works as expected and product name, logo, website and documentation links are Nethesis default
- Access Cockpit and verify that product name, logo and favicon are branded Nethesis
- Go to Cockpit **System** > **About** page
- Verify that 
  - Nethesis logo is shown
  - **Official site** links to https://nethesis.it/
  - **Documentation** links to https://docs.nethesis.it/
  - **Helpdesk** links to https://helpdesk.nethesis.it/
  - **Phone Home** section is NOT shown

**Comment by andre8244** [comment]
**Test case 5 (old Server Manager)**

Test branding and unbranding inside old Server Manager (https://server:980).
When branding is enabled, verify that logo, favicon and custom UI colors are displayed.

**Comment by andre8244** [comment]
**Testing RPM**
- [nethserver-cockpit](http://packages.nethserver.org/nethserver/7.8.2003/testing/x86_64/Packages/nethserver-cockpit-1.7.5-1.3.gf88d207.ns7.noarch.rpm)
- [nethserver-cockpit-lib](http://packages.nethserver.org/nethserver/7.8.2003/testing/x86_64/Packages/nethserver-cockpit-lib-1.7.5-1.3.gf88d207.ns7.noarch.rpm)
- [nethserver-register](http://packages.nethesis.it/nethserver/enterprise/7.8.2003/nethesis-testing/x86_64/Packages/nethserver-register-4.5.1-1.4.g3d917f6.ns7.noarch.rpm)
- [nethserver-subscription](http://packages.nethserver.org/nethserver/7.8.2003/testing/x86_64/Packages/nethserver-subscription-3.6.1-1.1.g234cfd7.ns7.noarch.rpm)
- [nethserver-subscription-ui](http://packages.nethserver.org/nethserver/7.8.2003/testing/x86_64/Packages/nethserver-subscription-ui-3.6.1-1.1.g234cfd7.ns7.noarch.rpm)
- [nethserver-httpd-admin](http://packages.nethserver.org/nethserver/7.8.2003/testing/x86_64/Packages/nethserver-httpd-admin-2.5.0-1.1.gc945a2c.ns7.noarch.rpm)

**Comment by gsanchietti** [comment]
The branding works correctly on launcher, cockpit and old server manager.
Excellent work!

**Comment by gsanchietti** [comment]
In nethserver-updates:
- nethserver-httpd-admin-2.5.1-1.ns7.noarch.rpm
- nethserver-cockpit-1.7.6-1.ns7.noarch.rpm
- nethserver-cockpit-lib-1.7.6-1.ns7.noarch.rpm
- nethserver-subscription-3.6.2-1.ns7.noarch.rpm
- nethserver-subscription-ui-3.6.2-1.ns7.noarch.rpm

In nethesis-updates:
- nethserver-register-4.6.0-1.ns7.noarch.rpm

In nethforge:
- nethserver-register-4.6.0-1.ns7.noarch.rpm
