### ISSUE TITLE
Report: malformed JSON string on nextcloud miner

### ISSUE THREAD

**Issue by gsanchietti** [nethesis/dev#5847]
The ciacco cronjob reports an error if nextcloud has not been updated or has been removed.
Bug introduced by #5842 

**Steps to reproduce**

- Install nethserver-dante and nethserver-nextcloud packages
- Access nextcloud at least one
- Remove nextcloud: `yum remove nethserver-nextcloud`
- Execute: `ciacco`

**Expected behavior**

No error should be raised.

**Actual behavior**

The `/usr/share/dante/miners/nextcloudsize-list` miner raises raises the following error:
```
malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "(end of string)") at /usr/share/dante/miners/nextcloudsize-list line 40.
```

**Workaround**

If nextcloud is installed, update it to the latest release: `yum update nethsever-nextcloud`.
If nextcloud is not installed, remove the data directory: `rm -rf /var/lib/nethserver/nextcloud`.

**Components**

dante-0.4.1-1.ns7.x86_64

**See also**

- https://community.nethserver.org/t/cron-daemon-reports-error-on-bin-ciacco-via-email/16021

----

Thanks to **france** and **Zoaky**

**Comment by gsanchietti** [comment]
In testing:
dante-0.4.1-1.1.g412414d.ns7.x86_64.rpm

**Comment by gsanchietti** [comment]
**Test case**
Check the bug is not reproducible

**Comment by nrauso** [comment]
Tested: **verified**

Miner does not raise any kind of error, now

**Comment by gsanchietti** [comment]
In nethserver-updates:
dante-0.4.2-1.ns7.x86_64.rpm

**Comment by gsanchietti** [comment]
The problem still persists even on machines where nextcloud is correctly installed.

**Comment by gsanchietti** [comment]
**Test case 2**
- Install nethserver-nextcloud, then update dante package from testing
- Overwrite dante cronjob to make to execute it every minute: `echo '* * * * *   root /usr/bin/ciacco' > /etc/cron.d/dante`
- Verify no mail is sent to root when the cronjob is executed. If mail server is not installed, just use `tail -f  /var/log/cron /var/spool/mail/root`

**Comment by gsanchietti** [comment]
In nethserver-testing:
dante-0.4.2-1.1.g9a68ce8.ns7.x86_64.rpm

**Comment by federicoballarini** [comment]
On our server now it works fine!

**Comment by gsanchietti** [comment]
In nethserver-updates:
- dante-0.4.3-1.ns7.x86_64.rpm
