### ISSUE TITLE
my.nethesis: no inventory data

### ISSUE THREAD

**Issue by filippocarletti** [nethesis/dev#5874]
my.nethesis server details page shows no data about inventory. Forcing inventory transmission results in no error, but the data is still not shown.
The problem is caused by a spurious file in /var/lib/nethserver/db (a vim .swp file in at least a couple of cases).

**Steps to reproduce**

- Add a "bad" db file:
```
echo -n "a=" >/var/lib/nethserver/db/.test
for i in $(seq 1 2000); do echo -ne "\0" >>/var/lib/nethserver/db/.test; done
```
- Run: `ardad --send`

**Expected behavior**

Inventory update

**Actual behavior**

No inventory

**Comment by edospadoni** [comment]
Test case:
- check the bug is not reproducible

**Comment by filippocarletti** [comment]
```
Updated:
  nethserver-subscription-inventory.x86_64 0:3.6.4-1.1.gd3e3eff.ns7    nethserver-subscription-ui.noarch 0:3.6.4-1.1.gd3e3eff.ns7   

Dependency Updated:
  nethserver-subscription.noarch 0:3.6.4-1.1.gd3e3eff.ns7           

[root@ns7-ent ~]# ardad --send

```

my.nethesis.it shows up-to-date inventory data

**Comment by gsanchietti** [comment]
Released:
nethserver-subscription-3.6.5-1.ns7.noarch.rpm
nethserver-subscription-inventory-3.6.5-1.ns7.x86_64.rpm
