### ISSUE TITLE
NethSpot + Flashstart not working if hotspot interface has an alias ip address

### ISSUE THREAD

**Issue by cotosso** [nethesis/dev#5899]
**Steps to reproduce**

- Enable nethspot and register it to an instance
- Enable flashstart content filter and apply to hotspot network
- Create an alias IP address to hotspot interface in order to manage APs (very often APs are on a different network and we need an additional ip address on the firewall to reach them,  exept if you are using vlans) 

**Expected behavior**

Everything works flawlessy

**Actual behavior**

If we define an alias on the hotspot interface name resolution stop to work, redirect on captive portal doesn't work too, it's impossible to go to the internet even if you are already authenticated (e.g. users with autologin)

**Components**

NethServer release 7.8.2003 (final)
nethserver-dedalo-1.3.5-1.ns7.noarch
nethserver-flashstart-2.2.3-1.ns7.noarch

**Comment by cotosso** [comment]
I tried to understand this problem and I found that the REDIRECT present in shorewall rules can't work if we have an alias ip.
```
?COMMENT Transparent DNS proxy on hotsp for port 53
REDIRECT        hotsp   10053   udp     53
```

Under these conditions unbound can't receive any forwarded packet and name resolution stops to work.
The fix that I'm using at the moment to make things work is to use a DNAT instead than REDIRECT and specifying the firewall destination ip address to send the traffic to (it's the coova-chilli ip adress : first of the hotspot network : default 192.168.182.1).

```
iptables -t nat -I hotsp_dnat -p udp --dport 53 -j DNAT --to-destination 192.168.182.1:10053
````

This way the forwarded traffic can reach unbound and the name resolution starts to work again.

**Comment by gsanchietti** [comment]
I do not get what is the problem in this scenario.
Does the traffic is correctly redirected to unbound?
If not, where the traffic is redirected?
If yes, why name resolution does not work? Is there any log which describes the problem?

**Comment by cotosso** [comment]
As soon as an IP alias is created on the hotspot interface the redirect to unbound stops working and unbound no longer receives any traffic.
To be more precise it can happens that sometimes traffic is sent to unbound (after waiting many seconds) and some page will open, but this is quite random and unpredictable, it doesn't work good anyway.
In the best case as soon as you try to go to a different domain you will be stopped and name resolution won't work.

May be the problem comes because we have 2 interfaces: 
* a tun interface with the ip address of the dedalo
* a physical interface without a main ip address but with an added ip address

I found the DNAT solution with the forced ip solves the problem and doesn't need to change unbound configuration.
I'm obviously open to any change that fix the problem.

**Comment by gsanchietti** [comment]
So if the traffic is not sent to unbound, where does it go?
Is there any evidence inside `/var/log/firewall.log` or inside iptables chains?

If there is still some traffic that reaches unbound, what is the different from this kind of traffic and the above one?

> May be the problem comes because we have 2 interfaces:
>    a tun interface with the ip address of the dedalo
>    a physical interface without a main ip address but with an added ip address

This is a very bad configuration, I'd say it is not supported and prone to errors.

**Comment by cotosso** [comment]
I can't see any block in the firewall.log.
The traffic is sent to the hotspot zone which includes physical interface (with alias ip) and tun-dedalo interface.
Since there is no stringent indication of the ip address to which it must be forwarded I can assume that it is redirected to one or the other ip but only the one of the tun-dedalo interface is the correct one and only configured on unbound .
If the traffic is redirected to the alias ip then it dies there with no further possibilities.
Regarding the implementation with the 2 interfaces it is the standard implementation which works perfectly with nethspot.
In this case (very rare) there are 2 variables (flashstart and ip alias on the physical interface) which go in conflict when used together.
We just need to harden the redirect part by forcing the correct ip address for the redirect and everything will work flawlessy.

**Comment by gsanchietti** [comment]
Reading the man page, the `REDIRECT` target is the right one: https://ipset.netfilter.org/iptables-extensions.man.html#lbDK

> In this case (very rare) there are 2 variables (flashstart and ip alias on the physical interface) which go in conflict when used together.
Exactly, this is a very rare case, so I'm strongly against on such change: most installations work flawlessly and I want to carefully avoid regressions.

You could also try to:
- add the address of the alias to the bypass list
- create a custom template of `/etc/e-smith/templates/etc/shorewall/rules/89flashstart` for such rare situations
- add a custom template fragment as `88flashstart` with the line suggested in the issue description

**Comment by cotosso** [comment]
@gsanchietti the manual says: 
`It redirects the packet to the machine itself by changing the destination IP to the primary address of the incoming interface`

very likely this is the point: what is the primary ip address of the zone hotsp? 

`REDIRECT        hotsp   10053   udp     53`

this zone contains 2 interfaces with different ip addresses
from /etc/shorewall/intefaces

```
.
hotsp   enp4s0  dhcp,nosmurfs,routeback
.
.
.
#
# 90dedalo
#
hotsp   tun-dedalo      tcpflags,nosmurfs
````

So it seems quite uncertain to me what is the primary ip address...

I perfectly understand what you mean about regressions,I must say that in every test I made I had no problem with that.
It seems quite a simple modification that increases the robustness of the implementation removing some uncertainty related to the double interface.

I also must admit that this strange behavior was **extremely** difficult to find and reproduce, I spent many hours with the partner to be able to identify it.
I'm pretty sure that, even if well documented, it would cause malfunctions and take a long time to resolve to anyone except me, just because I already encountered it before.
For this reason I would like to have this behaviour automatically managed.

**Comment by gsanchietti** [comment]
> very likely this is the point: what is the primary ip address of the zone hotsp?

That line is translated into 2 REDIRECT target inside iptables so each interface has its own rule.
If the traffic comes from tun, the primary address is the address of the tun itself.
If the traffic comes from the ethernet interfaces, the primary address is the one listen in `ip show` command.

> I also must admit that this strange behavior was extremely difficult to find and reproduce, I spent many hours with the partner to be able to identify it.

That's exactly the reason why I'm not going to change the implementation for anyone.

**Comment by cotosso** [comment]
> That line is translated into 2 REDIRECT target inside iptables so each interface has its own rule.
> If the traffic comes from tun, the primary address is the address of the tun itself.
> If the traffic comes from the ethernet interfaces, the primary address is the one listen in ip show command.

This is the theory, from a customer side the hotspot doesn't work at all and the problem is very difficult to identify even for our technicians.
May be you can find a better fix than mine (obviously not a template-custom)?

**Comment by gsanchietti** [comment]
We do not push changes to everyone for very isolated use cases.

You have 3 different options here:
- disable flashstart for hotspot zone
- create a template custom
- add the access point network inside the bypass list
