### ISSUE TITLE
First incoming call of the day not always ring on Chrome

### ISSUE THREAD

**Issue by alepolidori** [nethesis/dev#5923]
**Steps to reproduce**

- enable chrome to re-open last tabs each time you open it
- open cti in a tab
- open another tab on other destination site
- close chrome
- re-open chrome leaving cti in background
- from another cti make a call to your cti
- verify that no audio ringing is played

**Expected behavior**

An incoming call have always to ring

**Actual behavior**

Usually the first incoming call of the day does not ring. This is because of chrome autoplay policy: if you have never interacted with cti web interface, chrome does not allow you to play any audio sound (ringing sound in this case).

**Components**

nethcti3

**Comment by b9874e** [comment]
**cantfix:**
- At the moment for Chrome there isn't any way to play audio without visiting the tab after Chrome reopening.
- For Firefox there isn't any way to receive calls without visiting the tab after Firefox reopening.

In conclusion there isn't a cross browser solution to do this at the moment.
