### ISSUE TITLE
Change the location of the call history popup

### ISSUE THREAD

**Issue by tonyco97** [nethesis/dev#5978]
**Steps to reproduce**

- Go to the main page of the nethcti
- Click on history
- Go to the central table
- Go to the Contact column
- Choose any of the calls made and hover over them with the mouse
- A popup will come out which is now seen on the left side

**Expected behavior**

Change the position of the popup from the left side to the top, always keeping the central position respect to the call history

**Comment by tonyco97** [comment]
**How to test**
- Go to the main page of the nethcti
- Click on history
- Go to the central table
- Go to the Contact column
- Choose any of the calls made and hover over them with the mouse
- Now the popup is displayed above and is central to the writing
- The position of the popup has been changed for both the personal history and the collective history

**Comment by alepolidori** [comment]
in `7.9.2009/nethesis-testing`:
- nethcti3-3.23.0-1.8.g85694c1.ns7.noarch.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethcti3-3.23.0-1.8.g85694c1.ns7.noarch.rpm)
