### ISSUE TITLE
Nethvoice-docs: cosmetic fix 

### ISSUE THREAD

**Issue by tonyco97** [nethesis/dev#5984]
**Steps to reproduce**

- Go to nethvoice.docs.nethesis
- Search for the name of a very long chapter
- There will be a wrong indentation

**Expected behavior**

Correction of the indentation, so that in the case of very long titles the characters do not overlap each other

**Comment by tonyco97** [comment]
![Before](https://user-images.githubusercontent.com/36625268/113406028-10792e80-93ab-11eb-9fa9-8d88cb88a3f3.png)
![After](https://user-images.githubusercontent.com/36625268/113406033-13741f00-93ab-11eb-8d48-e922ac7bedcd.png)
This is how it look before and after the changes.

**Comment by gsanchietti** [comment]
Verified

**Comment by gsanchietti** [comment]
Released: https://github.com/nethesis/nethvoice-docs/pull/122
