### ISSUE TITLE
The miners dedicated to the mail return values 0

### ISSUE THREAD

**Issue by lucagasparini** [nethesis/dev#6035]
If the local System is set with `LANG = it_IT.UTF-8`, the miners that calculate the sums of the mails (received, sent, filtered, etc.) and also the sums of the attachments scanned by YOMI report a value of 0.
Within the miners the command `date` is used to compare the data reported in the maillog and this does not match (for example `Jun 21` instead of `Jun 21`).

**Steps to reproduce**
- set local system in Italian: `localectl set-locale LANG = it_IT.UTF-8`
- reboot the system
- send and receive at least one email
- run this miner for example: `/usr/share/dante/miners/mailreceived-counter | jq`

**Expected behavior**
- the miner reports the number of emails received as the sum value

**Actual behavior**
- the miner always reports 0 as a sum value

**Components**
`dante-0.5.0-1.ns7.x86_64`
`nethserver-dante-1.0.5-1.ns7.noarch`

**See also**
Workaround:
```
 cat /etc/e-smith/templates-custom/etc/cron.d/dante/10miners

# Execute all miners each day at 23:45
# Miners should be executed before the enf of day
45 23 * * *   root LANG=en_US.UTF-8 /usr/bin/ciacco
```

_Ticket Ref:_ https://helpdesk.nethesis.it/a/tickets/134392

**Comment by gsanchietti** [comment]
Moved to NethServer/dev#6533
