### ISSUE TITLE
Wrong handling of incoming call via "other" apps (eg: Nethifier)

### ISSUE THREAD

**Issue by NethNick** [nethesis/dev#6081]
When Nethifier is installed it handles the incoming calls via an "iframe" like window.
To reproduce need to have a Nethifier installed and handle an incoming call.
CTI sends a notification message, eg: `{"notification":{"id":"229<-203","url":"http://nethvoice.nethesis.it/webrest/static/templates/notification_popup/call.html?callerNum=203&ctiProto=https&callerName=203&mainExten=229&dialExten=229&answerAction=true&webrtc=true&random=1635429149278","width":"400","height":"174","action":"open","closetimeout":"10"}}`

This causes a msgbox to be opened to the "url" indicated: 
![image](https://user-images.githubusercontent.com/87082120/139270974-134a2d48-28e1-46f5-924d-503ce2a59e69.png)

As stated it should allow to answer or drop the call.

**Expected behavior**
- Answer and go straight to the call clicking "Rispondi"
- Drop the call clicking "Riaggancia"

**Actual behavior**
- If Firefox is used and CTI is not on focus, nothing happens until it get's back the focus (and then answers or drops the call as it should have done "immediately")
- Answering with the "popup" crashes Webrtc making it useless

**Comment by b9874e** [comment]
With the actual flow there isn't a way to enhance this behaviour due to Firefox policies, using Chrome this scenario is already managed.
