### ISSUE TITLE
Required support for USB headphones

### ISSUE THREAD

**Issue by NethNick** [nethesis/dev#6109]
There is a wide request to integrate telephony headset with Nethifier, preferably following fundamental and standardized USB HID commands to support a broad set of telephony devices (0x0B) with headset usage id (0x05). Minimal functions are required: answer/hangup and if supported natively by OS leave untoched other functions (volume +/- and or mute).
A plus may be using USB Raw Hid data so to avoid messing with connection/removal/suspend and leave the job to the underlying OS.
Reference: HID Usage Tables 1.22 from [www.usb.org](http://www.usb.org/)

**Comment by NethNick** [comment]
Howto test Nethifier USB Telephony Headset integration:

on a Microsoft Windows machine plug a USB Telephony Headset device
- check that matches the USB Telephony Headset Class
![UsbClass](https://user-images.githubusercontent.com/87082120/155511512-8ef98d7e-4ef4-45ac-8371-6beb2260c9f9.jpg)
It should have: the HID-compliant headset description and HID_DEVICE_UP:000B:0005 property

The Headset should have some buttons to interact with telephony calls, eg: Hook,Volume +-,Mute

If the On/Off Hook button follows USB specifications will be recognized by Nethifier and will answer or hangup the call opportunely.

**Comment by NethNick** [comment]
Howto test Token regeneration:

on a Microsoft Windows machine use Nethifier normally then lock/suspend PC for at least 15 min.

Log back and answer the first call (Nethifier should regenerate an expired token and use it transparently to answer the call).

It should work normally without any delay or abnormal message.

**Comment by viktec** [comment]
The new nethifier works fine with USB headphones. Everything works as expected, answer with the call button, mute the microphone during the call, no response delay.

**Comment by gsanchietti** [comment]
https://github.com/nethesis/nethifier/releases/tag/3.0.7

**Comment by NethNick** [comment]
Released new version (verified) and made PR
