### ISSUE TITLE
Keyboard shortcuts blocked by Nethifier

### ISSUE THREAD

**Issue by viktec** [nethesis/dev#6116]
**Steps to reproduce**

Keyboard shortucts are  by the Nethifier (Dialer Hotkey Section). 

- Open the Nethifier and set in the Dialer Hotkey section your combination to call
- Open a software which uses keyboard shorcuts, like the management system
- Perform some keys or key combinations that need to perform actions
- Shortcuts are blocked by Nethifier

**Expected behavior**

Any combination chosen on Nethifier's Dialer Hotkey must not interfere with other software in use.

**Components**

- Nethifier 3.0.6
- Nethifier 3.0.7

**See also**

nethesis/dev#6109

**Comment by gsanchietti** [comment]
Release to be tested: https://github.com/nethesis/nethifier/releases/tag/3.0.8

**Comment by gsanchietti** [comment]
**Test case**
Check the issue is not reproducible

**Comment by viktec** [comment]
The keyboard shortcuts are not blocked by nethifier, tested with management and works correctly
