### ISSUE TITLE
Disconnections after 1minute and 5 seconds during a call

### ISSUE THREAD

**Issue by bjzyo85** [nethesis/dev#6120]
**Steps to reproduce**

- During a call the download bandwidth go down a I can't hear contact person

**Expected behavior**

I expect the call continue until I hang up.

**Actual behavior**

// I can't hear contact person

**Components**

Version: NethCTI Android 1.3.0 (4190)

**Comment by gsanchietti** [comment]
There is not enough info to the debug it.
Also, this sounds much like a support request.

Please open a ticket at https://helpdesk.nethesis.it/
