### ISSUE TITLE
Phone registration issue in Asterisk 18.10.1.

### ISSUE THREAD

**Issue by cutehameed** [nethesis/dev#6125]
Hi, All. I am total new to VOIP & Asterisk and I have installed Asterisk 18.10.1 on ubuntu 18.04.06 LTS.
I am trying to register softphone (Zoiper) with server on same network but i am unable to to do. While debugging i come following errors.
``[Mar 17 10:47:15] NOTICE[20134]: res_pjsip/pjsip_distributor.c:676 log_failed_request: Request 'REGISTER' from '<sip:0019159BF771@192.168.1.121>' failed for '192.168.1.100:44331' (callid: tuQtB9LTAKYthGjL9IYN7Q..) - No matching endpoint found [Mar 17 10:47:15] NOTICE[20134]: res_pjsip/pjsip_distributor.c:676 log_failed_request: Request 'REGISTER' from '<sip:0019159BF771@192.168.1.121>' failed for '192.168.1.100:44331' (callid: tuQtB9LTAKYthGjL9IYN7Q..) - No matching endpoint found [Mar 17 10:47:15] NOTICE[20134]: res_pjsip/pjsip_distributor.c:676 log_failed_request: Request 'REGISTER' from '<sip:0019159BF771@192.168.1.121>' failed for '192.168.1.100:44331' (callid: tuQtB9LTAKYthGjL9IYN7Q..) - `
Please help me.

**Comment by gsanchietti** [comment]
Hello @cutehameed,
this is not an issue tracker for Asterisk 18, nor a support forum.

Please refer to Asterisk community: https://community.asterisk.org/
