### ISSUE TITLE
Yomi sandbox: presume attachment is clean on "Maximum hash retransmits exceeded"

### ISSUE THREAD

**Issue by andre8244** [nethesis/dev#6130]
In rare and currently unknown circumstances an email is never delivered because yomi plugin continuously reaches `Maximum hash retransmits exceeded` and performs a soft-reject.

**Proposed solution**

This issue seems to happen with clean attachments only. Avoid soft-reject and mark the e-mail with `YOMI_UNKNOWN` when `Maximum hash retransmits exceeded` is reached

**Comment by gsanchietti** [comment]
In nethesis-testing:
- nethserver-yomi-2.1.1-1.1.g91b4735.ns7.noarch.rpm

**Comment by andre8244** [comment]
**Test case**

- Edit `/usr/share/rspamd/lualib/lua_scanners/yomi.lua` and set `hash_retransmits = 0` (https://github.com/nethesis/yomi-rspamd/blob/master/yomi.lua#L37) to simulate the issue
- Run `signal-event -j nethserver-yomi-update` to apply the change
- Send and e-mail to this server with an attachment unknown to the sandbox (e.g. a binary file generated with `head -c 100K < /dev/urandom > binary_file`)
- Verify that this line is printed in `/var/log/maillog`: `Maximum hash retransmits exceeded for <ATTACHMENT_NAME>, presuming attachment is clean`
- Verify that the e-mail has been delivered with symbol: `YOMI_UNKNOWN(0.00)[Maximum hash retransmits exceeded for <ATTACHMENT_NAME>, presuming attachment is clean]`
- Reset `hash_retransmits = 7` in `yomi.lua`
- Re-run `signal-event -j nethserver-yomi-update` to apply the change

**Comment by lucagasparini** [comment]
Test passed successfully :+1:

**Comment by lucagasparini** [comment]
Test passed successfully :+1:

**Comment by gsanchietti** [comment]
Released:
nethserver-yomi-2.2.0-1.ns7.noarch.rpm
