### ISSUE TITLE
Status of operator panel is inconsistent 

### ISSUE THREAD

**Issue by Stell0** [nethesis/dev#6163]
https://github.com/nethesis/dev/issues/6155 seems to be still present

In this screen, Giovanni Gallozzi is no more in the call, as you could see 
![Screenshot 2022-06-09 at 10-07-19 NethCTI](https://user-images.githubusercontent.com/4547897/172828502-a1bc3eeb-8430-430d-8e03-6d0d631da621.png)

**Steps to reproduce**

It isn't clear to me how this issue happens, but switching between cti tabs is easy to spot people which phone state (upper part of the card) is inconsistent with the call state (lower part of the card). Refreshing the page fix the inconsistency

**Comment by b9874e** [comment]
It could happen occasionally after days of inactivity, refresh the page to fix the inconsistency. A fix will be implemented if the reports of this problem increase.
