### ISSUE TITLE
Nethifier: Checkbox not reflecting Ringtone configuration

### ISSUE THREAD

**Issue by NethNick** [nethesis/dev#6164]
**Steps to reproduce**
- Open Nethifier, edit settings, set Ringrone popup position to "none"
- Close software and reload settings, there will be a "default checkbox" (bottom right) not reflecting saved config

**Expected behavior**

After reloading no checkbox in Ringtone tab should be checked

**Actual behavior**

After reloading actually there's a default checkbox in Ringtone not reflecting saved config

**Components**

Nethifier 3.1.0

**Acknowledgements**

Thanks to Angelo Bollettini for the notice!

**Comment by andrea-marchionni** [comment]
Version 3.1.1
