### ISSUE TITLE
NethVoice broken after restore-data 

### ISSUE THREAD

**Issue by Stell0** [nethesis/dev#6172]
After restoring a backup, NethVoice "Apply changes" is broken

**Steps to reproduce**

- Do a backup
- on a new machine restore the backup.

retrieve conf will fail with this error:
```
exit: 1
Unable to continue. json_decode() expects parameter 1 to be string, array given in /var/www/html/freepbx/admin/modules/sipsettings/Sipsettings.class.php on line 435 #0 [internal function]: Whoops\Run->handleError(2, 'json_decode() e...', '/var/www/html/f...', 435, Array) #1 /var/www/html/freepbx/admin/modules/sipsettings/Sipsettings.class.php(435): json_decode(Array, true) #2 /var/www/html/freepbx/admin/libraries/BMO/DialplanHooks.class.php(107): Sipsettings->doDialplanHook(Object(extensions), 'asterisk', 900) #3 /var/lib/asterisk/bin/retrieve_conf(860): FreePBX\DialplanHooks->processHooks('asterisk', Array) #4 {main}
```

**See also**

https://helpdesk.nethesis.it/a/tickets/151739

**Comment by Stell0** [comment]
Test case:
- do the backup
- Enable `nethserver-testing` repository in `/etc/yum.repos.d/NethServer.repo` configuration file
- try disaster recovery
- verify that the bug doesn't show up

**Comment by Stell0** [comment]
[freepbx-14.0-12.2.gae9407e.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.9.2009/testing/x86_64/Packages/freepbx-14.0-12.2.gae9407e.ns7.noarch.rpm)

**Comment by nrauso** [comment]
Test case **verified**
The disaster recovery was completed flawlessly.

**Comment by Stell0** [comment]
[freepbx-14.0-13.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.9.2009/updates/x86_64/Packages/freepbx-14.0-13.ns7.noarch.rpm)
