### ISSUE TITLE
Param url isn't opened in some cases

### ISSUE THREAD

**Issue by b9874e** [nethesis/dev#6197]
**Steps to reproduce**

- Configure a trunk and set an extensions as destination
- Configure a param url and set open on ringing
- Make an inbound call through the configured trunk
- Note that the param url isn't opened on ringing

**Expected behavior**

- The param url must open on ringing in two cases:
    - When the call is through queue
    - When the call is through trunk

**Actual behavior**

- The param url isn't opened on ringing when the call is is through trunk

**Components**

nethcti-server
astproxy
nethcti

**Comment by b9874e** [comment]
Testing packages: 
- nethcti-server3: http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethcti-server3-3.28.7-1.13.g9217c1d.ns7.x86_64.rpm
- nethcti-server3-debuginfo: http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethcti-server3-debuginfo-3.28.7-1.13.g9217c1d.ns7.x86_64.rpm

**Comment by Stell0** [comment]
in `7.9.2009/nethesis-updates`:
- nethcti-server3-3.28.8-1.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-updates/x86_64/Packages/nethcti-server3-3.28.8-1.ns7.x86_64.rpm) 
- nethcti-server3-debuginfo-3.28.8-1.ns7.x86_64.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-updates/x86_64/Packages/nethcti-server3-debuginfo-3.28.8-1.ns7.x86_64.rpm)
