### ISSUE TITLE
Missing UI for google speech STT

### ISSUE THREAD

**Issue by tonyco97** [nethesis/dev#6205]
At the moment there is no interface for the speech to text function of the voicemail inside the wizard. 
The UI will show: 
- A card that allows uploading google's auth json file
- A card to enable or disabled the google speech recognition feature for voicemail attachment if the google's auth json file it's been already uploaded

**See also**

More info about the API's here: https://github.com/nethesis/nethvoice-wizard-restapi/#enable-or-disable-google-speech-stt-for-voicemail-attachment:~:text=enable%20or%20disable%20google%20speech%20STT%20for%20voicemail%20attachment

More info about Google Speech here: https://cloud.google.com/speech-to-text/docs/before-you-begin?hl=it#linux-or-macos

**Comment by Stell0** [comment]
[nethvoice-wizard-ui-14.15.0-1.8.ge48acb6.ns7.noarch.rpm](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethvoice-wizard-ui-14.15.0-1.8.ge48acb6.ns7.noarch.rpm)

**Comment by andrea-marchionni** [comment]
New version has new approach to this festure
