### ISSUE TITLE
Crash when login on iPhone

### ISSUE THREAD

**Issue by dmauro13** [nethesis/dev#6227]
**Steps to reproduce**

- Open the app
- Insert Domain
- Insert User
- Insert password
- Click login

**Expected behavior**

I expect to login in the app

**Actual behavior**

The app crash and close. Also i try the QRCode login but i do not found the i have to read it from the site.

**Components**

NethCTI iOS version 4.7.6(38)
Linphone SDK 5.2.1

iPhone 15 Pro - iOS 17.4.1

**Comment by dmauro13** [comment]
Any news?

**Comment by andrea-marchionni** [comment]
Hi @dmauro13 ,
the version of the app you are referring to has been replaced.
The new App ([click here](https://apps.apple.com/it/app/nethvoice/id6476514784)) has abandoned the previous project, I would ask you to contact our support to have all the details and possibly the update procedure.
